# Generated by Django 4.1 on 2023-12-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('element', models.CharField(max_length=50, verbose_name='Elemento')),
                ('description', models.TextField(max_length=100, verbose_name='Descricao')),
                ('type', models.CharField(choices=[('ARM', 'Arma'), ('ARD', 'Armadura'), ('CON', 'Consumivel')], max_length=3, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['id'],
            },
        ),
    ]
