# Generated by Django 4.1 on 2023-12-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Em andamento', max_length=20, null=True, verbose_name='Status')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
            options={
                'verbose_name': 'Jogador em Partida',
                'verbose_name_plural': 'Jogadores em Partidas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('playermatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playermatches.playermatch')),
            ],
            options={
                'verbose_name': 'Partida do Jogador',
                'verbose_name_plural': 'Partidas do Jogador',
                'ordering': ['id'],
            },
        ),
    ]
